### ISSUE TITLE
full width boxes on mobile

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#1]
the top box should be full width on mobile like the other boxes

<img width="400" alt="screen shot 2015-08-13 at 11 54 23 pm" src="https://cloud.githubusercontent.com/assets/2228347/9268700/ac6c1b5a-4216-11e5-8df5-6b501c97e330.png">

**Comment by schlosser** [comment]
Should the link be inline or below?

**Comment by jhil** [comment]
either works
