### ISSUE TITLE
copy/content

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#11]
everywhere

**Comment by ajayanti** [comment]
"fine" companies --> "awesome" companies (Sponsorship section)

**Comment by ajayanti** [comment]
Slim down About section (new version in google doc)

**Comment by ajayanti** [comment]
Change Hacking Begins -- 12:00 PM; Hacking Ends -- 12:00 PM; Demos -- 1:00 PM; Closing 3:00 PM

**Comment by ajayanti** [comment]
FAQ slim down -- all changes in google doc:
(1) "Do I need to know how to code to participate?" answer
(2) "How do I register?" answer
(3) "How do teams work?" answer

**Comment by ajayanti** [comment]
Maybe add a section where people can submit their own question? "Do you have a question that was not answered in our FAQ? Submit it here. We will get back to you ASAP."  link to Google form

**Comment by schlosser** [comment]
That should probably be a "don't see your question here?  email us!"  kind of thing.  Much simpler I think

**Comment by ajayanti** [comment]
Yeah okay, that works!
