### ISSUE TITLE
brighten blue variable

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#15]
use #00F2F2 for anything that is #3ae1ec

**Comment by schlosser** [comment]
Hmm, I just noticed that sometimes I'm using #00ffff and sometimes I'm using #3ae1ec. Should I just use #00ffff everywhere, #00f2f2 everywhere, or just change existing #3ae1ec to #00f2f2?

**Comment by jhil** [comment]
Every single thing should be pure cyan (#00ffff) except the CTA which should be slightly darker (#00f2f2).
