### ISSUE TITLE
replace sponsor logos

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#17]
github, a16z and kpcb are not yet on board

**Comment by schlosser** [comment]
replace -> remove?

**Comment by jhil** [comment]
not sure. but it needs to be solved. i'll talk to amritha.

**Comment by ajayanti** [comment]
We are talking to GitHub on Monday and KPCB is currently circulating to portfolio companies. a16z has been hard to reach - Mackenzie said she will send a follow up to see where they are... I would say remove and just keep AWC, Startup Shell, etc. under that section.

**Comment by jhil** [comment]
yup
