### ISSUE TITLE
SVG still has spacing below it

### ISSUE THREAD

**Issue by schlosser** [gotechnica/technica-site-2017#22]
I think this is a problem with the image.  If not, we can just cheat with a negative margin on the bottom.  It's a retina problem (only shows up at some screen widths).

![screen shot 2015-08-15 at 1 24 17 am](https://cloud.githubusercontent.com/assets/2433509/9288151/06987034-42ed-11e5-8362-672e2d9e747f.png)

**Comment by jhil** [comment]
fixed
