### ISSUE TITLE
jiggly team faces

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#28]
wuttt

![aug 17 2015 20 25](https://cloud.githubusercontent.com/assets/2228347/9321662/6a9c63be-451e-11e5-8933-08e22dd4d76d.gif)

**Comment by jhil** [comment]
@danrschlosser any ideas?

**Comment by schlosser** [comment]
What browser is that?

**Comment by jhil** [comment]
did we figure this out? it's still happening on my computer.

**Comment by schlosser** [comment]
I think it's a wonky chrome bug due to the transforms.  Unless we see this in other browsers I'm not sure what to say.

**Comment by schlosser** [comment]
The elements aren't moving, rather the way the images are rendered is... that screams chrome bug to me, but I could be wrong.

**Comment by jhil** [comment]
Seems like a rendering issue, but it still freaks me out. Leaving this open in case someone eventually can solve it!
