### ISSUE TITLE
head expand animation

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#3]
![Uploading Screen Shot 2015-08-13 at 11.55.19 PM.png…]()
on hover, box should animate in and headshot should expand 10px in all directions around its center (width + 20px in ems)

**Comment by jhil** [comment]
like this: https://dribbble.com/shots/2182102-UI8-v5-About

**Comment by schlosser** [comment]
Can I get that screenshot that failed to upload?

**Comment by schlosser** [comment]
what does "animate in" mean?  And you just want the profile picture bigger on hover?

**Comment by jhil** [comment]
oh no worries, i was just referencing the state.

<img width="288" alt="screen shot 2015-08-13 at 11 55 19 pm" src="https://cloud.githubusercontent.com/assets/2228347/9269229/52745d6e-421c-11e5-8278-149d24d1772e.png">

**Comment by jhil** [comment]
1. animate in like this: https://dribbble.com/shots/2182102-UI8-v5-About. i think it expands from the center, but isn't overdramatic. can't quite figure it out, any ideas?
2. profile picture bigger on card hover, yes. this may involve shrinking them in the normal state (while still occupying the same space).

**Comment by jhil** [comment]
got it
