### ISSUE TITLE
HTTPS Support on gotechnica.org

### ISSUE THREAD

**Issue by eveninglily** [gotechnica/technica-site-2017#42]
Should setup https support for gotechnica.org, as well as any subdomains (i.e. for the expo app). 

https://letsencrypt.org/ is free, supports wildcard domains, and is super easy to setup, no matter what the site is hosted on.

**Comment by ng-david** [comment]
Awaiting DNS propagation from Namecheap; Option on ghpages should be available in a few hours

**Comment by ng-david** [comment]
Update; waiting support from GitHub after following the expected steps failed.

Referenced this: https://github.community/t5/Pages/How-to-enable-https-support-on-custom-domains/m-p/6923#M463

**Comment by ng-david** [comment]
all is well now
