### ISSUE TITLE
use svg logo instead of png

### ISSUE THREAD

**Issue by jhil** [gotechnica/technica-site-2017#7]
here: 

<img src="img/logo-white.png" title="">

**Comment by jhil** [comment]
in header

**Comment by schlosser** [comment]
Can you give me a new svg where there isn't _any_ space on top / bottom?

**Comment by jhil** [comment]
wanna just use technica-logo-white-colorstripe.svg and change the fill to white with svg? wouldn't that save load?

**Comment by jhil** [comment]
put in the svg, just need to figure out how to make it white. fills and svg css are not working for me right now.
